# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
theme: jekyll-theme-minimal
title: Luxiang Lin
#email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  This is my personal blog containing some technical thinkings
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://linluxiang.github.io" # the base hostname & protocol for your site
github_username:  linluxiang

# Build settings
markdown: kramdown
